### ISSUE TITLE
style.css gone missing

### ISSUE THREAD

**Issue by ms-studio** [LeaVerou/whathecolor#6]
It seems that style.css was renamed in commit 883f986 fours days ago.

PS: came here via [your awesome talk](https://www.youtube.com/watch?v=8xjR7QXQKJ0) from 2014.

**Comment by LeaVerou** [comment]
> It seems that style.css was renamed in commit [883f986](https://github.com/LeaVerou/whathecolor/commit/883f986452829811068c070b2e45e92553cffd17) fours days ago.

It's just removed from the repo, as it's now built from PostCSS. I should add a redirect for GitHub Pages. Use whathecolor.com to access it, which is served from Netlify and includes build artifacts.

> PS: came here via [your awesome talk](https://www.youtube.com/watch?v=8xjR7QXQKJ0) from 2014.

Wow, what a blast from the past! 😊

**Comment by ms-studio** [comment]
Oh, thanks for the new link!
